name: Zip Artifacts

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Zip files
      run: |
        zip -r artifact.zip . -x "*.git*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: More-Useful-Recipes-dev.zip
        path: artifact.zip
