name: Zip Artifacts

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Zip files
      run: |
        zip -r artifact.zip path/to/directory -x "*.git*"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-zip-file
        path: artifact.zip
