name: Create and Store ZIP

on:
  push:
    branches: [ main ]

jobs:
  package-files:
    runs-on: ubuntu-latest
    name: Package specified files
    
    steps:
    - uses: actions/checkout@v4
    
    - name: List repository contents (for debugging)
      run: ls -R
      
    - name: Create ZIP file
      run: |
        FILES="data/ README.md pack.mcmeta pack.png LICENSE"
        
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        ZIPFILE="build_${TIMESTAMP}.zip"
        
        echo "Creating ${ZIPFILE} with files: ${FILES}"
        zip -r ${ZIPFILE} ${FILES}
        
        ls -lh *.zip
        
        echo "ZIPFILE=${ZIPFILE}" >> $GITHUB_ENV
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-package
        path: ${{ env.ZIPFILE }}